# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.TextField(verbose_name='object id')),
                ('action_object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('target_object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verb', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_action_action_type', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_action_actor_type', to='contenttypes.ContentType')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_action_target_type', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.TextField(verbose_name='object id')),
                ('action_object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('target_object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verb', models.CharField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_notification_action_type', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_notification_actor_type', to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_notification_target_type', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
    ]
